import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tax Orchard",
  description: "Generated by create next app",
  other: {
    "font-preload": "/fonts/SCHABO-Condensed.woff",
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/SCHABO-Condensed.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-regular.ttf"
          as="font"
          type="font/truetype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-light.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-bold.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-boldit.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-extrabold.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-black.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/proximanova-blackit.otf"
          as="font"
          type="font/opentype"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`antialiased relative`}>{children}</body>
    </html>
  );
}
