import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative`}>{children}</body>

      {/* <script async src="/js/smooth-scroll.js"></script> */}
      {/* <script async src="/js/scroll-reveal.js"></script> */}
      {/* <script async src="/js/form-animation.js"></script> */}
      {/* <script async src="/js/harvest-animation.js"></script> */}
    </html>
  );
}
